### ISSUE TITLE
Bug: Double Hyphen

### ISSUE THREAD

**Issue by pseymour** [devRant/devRant#41] opened 2017-08-05 12:22 UTC
On iOS when submitting a rant or comment that contains a double hyphen ( -- ), all text following will be truncated.

**Comment by DFoxinator** [comment] 2017-08-05 14:24
Thanks for the report - can you please provide some more info/a screenshot?

I can't think of what would cause this and I wasn't able to reproduce it.

**Comment by pseymour** [comment] 2017-08-05 14:33
this is quite a strange one.

rant with issue: 
https://www.devrant.io/rants/756726/rant

Screenshot of full rant: 
https://image.ibb.co/kkcRjv/20631855_10159099455125035_2036981930_n.jpg

looking at it on web, it appears to be re-interpreted as a single character.

**Comment by DFoxinator** [comment] 2017-08-05 14:36
Hmmm this is very weird. Are you sure it's not your device converting it before it gets sent? Because the -- was definitely converted to a single character before the rant text was stored.

**Comment by pseymour** [comment] 2017-08-05 14:49
bit of mucking around.
iOS is converting the -- to an **em dash** with its new smart punctuation feature.

**Comment by DFoxinator** [comment] 2017-08-07 02:42
@pseymour thanks for figuring that out! I'm going to close this issue, unless you think there's anything we can do about it, let me know if so.

**Closed by DFoxinator** 2017-08-07 02:42 UTC
Labels: bug, iOS app, need more info
