### ISSUE TITLE
Sometimes users with no avatars shows up as a broken image in notifications

### ISSUE THREAD

**Issue by tisaconundrum2** [devRant/devRant#337] opened 2018-03-06 20:30 UTC
Image provided of this situation
![image](https://user-images.githubusercontent.com/11879769/37056675-580d2bc2-2142-11e8-9ca7-4934b9b924f8.png)

**Comment by cozyplanes** [comment] 2018-03-07 12:46
Duplicate of #336

**Closed** 2018-03-11 19:22 UTC
Labels: Web app, bug
