### ISSUE TITLE
[Web app] [Bug] Tag filtering not effective on web version

### ISSUE THREAD

**Issue by TheOct0** [devRant/devRant#501] opened 2018-08-23 13:42 UTC
Hello,

The issue is just that when I filter out jokes/memes in the web version (or any other tag, actually), the filtering isn't effective. That is true even after reloading the website, logging out and in again, and so on.

**Comment by Skayo** [comment] 2018-08-23 15:49
Duplicate of #484

**Closed by Skayo** 2018-08-23 15:49 UTC
