### ISSUE TITLE
Webversion adds unnecessary newlines

### ISSUE THREAD

**Issue by Parou** [devRant/devRant#461] opened 2018-06-25 08:12 UTC
Since the new webversion, everytime I want to make a comment with manual newlines, it adds empty newlines between each line.

Input:
```
1 Begin
2 cuddle @Proximyst
3 Goto 1
4 End
```

Expected:
```
1 Begin
2 cuddle @Proximyst
3 Goto 1
4 End
```

Result:
```
1 Begin

2 cuddle @Proximyst

3 Goto 1

4 End
```

![newline](https://user-images.githubusercontent.com/28531401/41838282-44688880-7860-11e8-9fd6-1c0ab6e91140.PNG)

**Comment by Skayo** [comment] 2018-07-14 20:03
Annoying bug. Pretty high priority.
Temporary fix is to edit the comment on mobile.

**Comment by Skayo** [comment] 2018-07-17 22:03
Duplicate of #384

**Closed** 2018-07-17 22:05 UTC
Labels: Priority 1, Web app, bug
