### ISSUE TITLE
Ability to save avatar face closeup

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#31] opened 2017-08-03 09:42 UTC
I wonder if you can add a feature to save only the face closeup instead of full avatar as seen in rant/comments.

**Comment by DFoxinator** [comment] 2017-10-22 17:17
Duplicate of https://github.com/devRant/devRant/issues/187

**Closed by DFoxinator** 2017-10-22 17:17 UTC
Labels: Android app, API, feature, iOS app

**Comment by cozyplanes** [comment] 2017-10-23 10:00
hmmm i made a new issue... strange me
