### ISSUE TITLE
[feature request] Filter notifs

### ISSUE THREAD

**Issue by calmyourtities** [devRant/devRant#113] opened 2017-09-24 21:09 UTC
I can honestly say I don't care if some rant user ++'s my rant from two months ago. I like devRant in part because I can have conversation with other devs, which is why I'm mostly interested in people who either commented on my rant or mentioned me in a comment. I don't like having to scroll through every single notif to see them though. I'd like to be able to filter my notifs by type (comment on my rant, ++ on comment, ++ on rant, ++ collab, mentioned in collab, etc). If this feature is ever implemented, my suggestion for the UI would just be having a check box for every type of notif and only show the checked ones. 

- calmyourtities

**Comment by DFoxinator** [comment] 2017-10-23 05:28
duplicate of https://github.com/devRant/devRant/issues/5

**Closed by DFoxinator** 2017-10-23 05:28 UTC
Labels: Android app, API, feature, iOS app, Priority 2
