### ISSUE TITLE
[Feature request] Add downvote option for wrongly tagged posts

### ISSUE THREAD

**Issue by emmi-ari** [devRant/devRant#528] opened 2018-10-27 19:06 UTC
When downvoting a "Wrong category" option would be useful, because as of now, none of these downvote options is really suitable for wrongly tagged posts. 

**Platform:** Android, iOS, Web app

**Comment by jonasgeiler** [comment] 2018-10-29 10:20
Duplicate of #409

**Closed as completed** 2018-10-29 10:20 UTC
