### ISSUE TITLE
Multiple mentions when reply

### ISSUE THREAD

**Issue by SylarRuby** [devRant/devRant#263] opened 2017-12-03 07:55 UTC
iOS: When you hit a reply, close it, hit reply again, repeat this, and youll up with many mentions in the reply along with your message.

**Comment by Kimmax** [comment] 2017-12-04 19:29
I think that's expected

**Comment by DFoxinator** [comment] 2017-12-09 06:27
Thanks for the report - closing as duplicate of https://github.com/devRant/devRant/issues/39

**Closed by DFoxinator** 2017-12-09 06:27 UTC
