### ISSUE TITLE
Android: Comments on post are duplicated when hitting refresh multiple times

### ISSUE THREAD

**Issue by Hunt0** [devRant/devRant#521] opened 2018-10-08 16:43 UTC
**Expected behaviour:**
Comments only show once on post

**Actual behaviour:**
Comments show duplicates

**Description of bug:**
Pressing refresh multiple times will show load duplicate comments

**Steps to reproduce:**
1. Open a post
2. Hit refresh multiple times (basically hit refresh while refresh is taking place it seems)
3. Comments are duplicated, it seems as many times as the refresh button was pressed.

**Platform:** 
Android

**Additional Platform Info:**
Pixel XL 
Android 9

**App version:** ...
1.12.3.1

**Screenshots:**
![screenshot_20181008-123831](https://user-images.githubusercontent.com/6516992/46622178-9a582180-caf7-11e8-8844-09c3bd274bcd.png)

I'm assuming this should be a pretty easy fix by either disabling the button while refresh is taking place or just preventing it from doing anything if they press it while refreshing.

**Comment by jonasgeiler** [comment] 2018-10-08 20:58
Duplicate of #233

**Closed as completed** 2018-10-08 20:58 UTC
Labels: duplicate
