### ISSUE TITLE
Glitch when exiting edited comment page

### ISSUE THREAD

**Issue by coolq1000** [devRant/devRant#193] opened 2017-10-20 12:50 UTC
So, when I finish editing a comment I press back from the page in which I have the *edited* comment, it goes back to a page which has the *unedited* comment. So I am required to exit that window too.

If it changes anything, I'm using Android.

**Comment by SHRipper** [comment] 2017-11-23 20:05
Yep, also noticed that.

**Comment by Skayo** [comment] 2018-07-15 23:57
Duplicate of #32

**Closed by Skayo** 2018-07-15 23:57 UTC
Labels: Android app, Priority 2, bug
