### ISSUE TITLE
Close image preview with swipe

### ISSUE THREAD

**Issue by Anbacken** [devRant/devRant#133] opened 2017-10-02 10:47 UTC
As stated in the title it would be nice to be able to swipe upwards to close a full a screen image. On mobile screens like iPhone 6+ you’ve to stretch to reach top left corner. For example reddit mobile app has this feature and it works like a charm.

**Comment by DFoxinator** [comment] 2017-10-17 13:39
Thanks for the suggestion. Closing as duplicate of https://github.com/devRant/devRant/issues/55

**Closed by DFoxinator** 2017-10-17 13:39 UTC
Labels: feature, iOS app
