### ISSUE TITLE
[Feature Request] New report option

### ISSUE THREAD

**Issue by inpothet** [devRant/devRant#272] opened 2017-12-13 16:00 UTC
In the last couple of weeks/months the amount of reposts and 9gag memes have started to rise a lot,
Maybe a report option related to the about of "9gag memes" because they start to become somewhat annoying.

And yes i know i have done it in the past but those were at-least dev/sysadmin related

**Comment by alberto98fx** [comment] 2017-12-13 16:09
I'm not interested in DevRant anymore since it's full of memes, deleted my account because I don't want a 9gagrant :) 

Or at least create categories and throw them in the void.

**Comment by watzon** [comment] 2017-12-13 16:26
I second this. While I think that the community needs to be inclusive and newbie friendly there should be a line. I use to be pretty active, but I've had the same problem as @alberto98fx where I got tired of the constant memes, reposts, etc.

**Comment by RekkyRek** [comment] 2017-12-13 16:28
There should really be a filter to hide everything posted as a "meme". It's actually really annoying and i down vote all i see (that's not original and actually funny)

**Comment by DFoxinator** [comment] 2017-12-13 16:39
Closing as duplicate of https://github.com/devRant/devRant/issues/264. We already are adding this option. @alberto98fx we added categories a few months ago - filtering by category is coming soon.

**Comment by JakubSteplowski** [comment] 2017-12-13 16:39
They're working on the categories, so you will be able to filter rants not to see memes if you don't want to.
I think they will release an update with this feature before the end of the year along with the new version of the web version, this is my guess.

**Closed** 2017-12-13 16:39 UTC
