### ISSUE TITLE
[Webapp] Missing subscribing to an user

### ISSUE THREAD

**Issue by joas8211** [devRant/devRant#382] opened 2018-04-10 19:19 UTC
Title explains it. But I'll repeat:
Web app is missing a feature for subscribing to an user.

**Comment by 7twin** [comment] 2018-04-10 22:38
Duplicate of #352 and #372

**Comment by joas8211** [comment] 2018-04-10 22:58
Closing as duplicate of #352.

**Closed** 2018-04-10 22:58 UTC
