### ISSUE TITLE
Cannot change the picture in a comment.

### ISSUE THREAD

**Issue by Darvesh696** [devRant/devRant#309] opened 2018-01-23 12:56 UTC
When I tried to attach new pic by modifying a comment, it showed the old pic, not the one I uploaded.

Android 7.0

**Comment by DFoxinator** [comment] 2018-02-13 05:41
Thanks for reporting. Closing as duplicate of https://github.com/devRant/devRant/issues/144

**Closed by DFoxinator** 2018-02-13 05:41 UTC
