### ISSUE TITLE
Subscribe to rant feature 

### ISSUE THREAD

**Issue by sasin91** [devRant/devRant#90] opened 2017-09-07 06:23 UTC
A subscribe to rant feature would be welcome.
This feature would mitigate the need for people to "bump" rants, to receive updates :)

I imagine a user_rants pivot table would suffice.
but for brevity, this could be promoted to a rant_subscriptions model? :)

**Comment by cozyplanes** [comment] 2017-09-07 10:25
Possible duplicate of #6

**Comment by cozyplanes** [comment] 2017-09-08 04:11
@DFoxinator where are you? cant see you latelu

**Comment by DFoxinator** [comment] 2017-09-14 04:09
@sasin91 sorry I told you to make this, didn't realize it was already issued - I'm going to change the title of https://github.com/devRant/devRant/issues/6 to be more searchable.

**Closed by DFoxinator** 2017-09-14 04:09 UTC
