### ISSUE TITLE
Double tap in a rant causes the rant to open twice

### ISSUE THREAD

**Issue by cozyplanes** [devRant/devRant#226] opened 2017-11-03 10:05 UTC
1. upvote a rant by pressing the upvote button in rant view
2. then double tap twice (so 4 taps)
3. the rant will open. 
4. press the in app/device back button
5. you can find that the rant is opened twice.

It seems to happen both in [android](https://www.devrant.io/rants/862478) and in [iOS](https://github.com/devRant/devRant/issues/192)

**Comment by DFoxinator** [comment] 2017-11-04 17:36
Duplicate of https://github.com/devRant/devRant/issues/192

**Closed by DFoxinator** 2017-11-04 17:36 UTC
