### ISSUE TITLE
Quick Tab Switching results in empty view

### ISSUE THREAD

**Issue by n0ah01** [devRant/devRant#228] opened 2017-11-03 23:09 UTC
When I switch between (for example) the normal feed any the collab tab quickly (<0.3s maybe), I get an empty gray view, until I re-tab on the feed/collab again. 

I have an BQ Aquaris X5 with Lineage OS 14.1 and the latest devRant App installed.

![The View I get](https://i.imgur.com/sNo3JHw.png)

Let me know if you need additional info ;-)

**Comment by cozyplanes** [comment] 2017-11-04 00:10
@DFoxinator

How about making all buttons in bottom nav bar 
to onClick instead of onFingerAboveFinger

Maybe it will fix the issue

**Comment by DFoxinator** [comment] 2017-11-08 05:50
Thanks, closing as duplicate of https://github.com/devRant/devRant/issues/7

**Closed by DFoxinator** 2017-11-08 05:50 UTC
