### ISSUE TITLE
Notification timestamps don't update upon refresh

### ISSUE THREAD

**Issue by NickWu007** [devRant/devRant#259] opened 2017-11-23 19:15 UTC
Hi there,

I am new to the site and was scrolling through my notifications earlier today and saw this. (Android 8.0 Native app)

![r_1025461_urwvo](https://user-images.githubusercontent.com/17936144/33186620-b5a6c326-d082-11e7-885e-ea9e94550f8e.jpg)

The top notification is new when refreshed, but clearly the timestamp for the second notification cannot be correct, given it was created before the second one. It looks like when fetching new notifications, the app forgets to update timestamps for old ones. 

However, this does not seem to be reproducible, which is quite strange. I guess the timestamps are fixed when the app is restarted?

Hope this helps,
Nick

**Comment by DFoxinator** [comment] 2017-12-09 06:25
Thanks for the report - yeah, the notifs don't have any updating functionality, so once one is loaded, its timestamp doesn't change.

Going to close this as a duplicate of https://github.com/devRant/devRant/issues/60

**Closed by DFoxinator** 2017-12-09 06:25 UTC
