### ISSUE TITLE
[Bug][Web App] Scrolling Error

### ISSUE THREAD

**Issue by kaitoyonde** [devRant/devRant#516] opened 2018-09-23 18:46 UTC
**Expected behavior:**
the page supposed to be scrolled normally from top to bottom
**Actual behavior:**
the page scroll jumping/vibrating up and down on specific rant, not all rant are affected. the list is in the description
**Description of bug:**
I cannot quantize what the specific reason to raise the bug, so I have made this short list of where the bug exist and where is not. tested on my browser.
- **Bugs On**:
  - Long Post
  https://devrant.com/rants/1789467/look-i-know-im-just-a-newbie-i-started-a-year-ago-as-a-junior-sure-no-one-wants
  - Short Post - Comment Contain Pic
  https://devrant.com/rants/1785821/i-decided-to-build-a-mechanical-keyboard-myself-almost-done-with-the-pcb-design
  - Short Post - Comment Contain Long Word
  https://devrant.com/rants/1772005/need-help-setting-up-my-server-so-i-already-got-my-ddns-and-domain-after-dns-red
  - Long Post - Long Comment
  https://devrant.com/rants/1765005/got-first-assignment-on-my-first-meet-on-network-security-it-require-to-pentest
  - Long Post
  https://devrant.com/rants/1757296/i-took-database-system-class-and-courses-in-university-and-told-to-store-the-pas
  - Short Post/Pic - Long Comment -- Bug only appear at the bottom
  https://devrant.com/rants/1667706/ive-been-coding-for-the-last-19-hours-not-including-break-and-now-i-am-starting
  - Short Post - Short Comment
  https://devrant.com/rants/1762801/my-office-setup-is-finished-and-i-have-my-first-client-they-ask-about-how-much-t
- **Not Bug**:
  - Short Post/Pic - Long Comment
  https://devrant.com/rants/1775205/i-wonder-when-there-will-be-the-first-manufacturer-to-introduce-the-cool-new-not
  - Short Post - Long Comment
  https://devrant.com/rants/1778744/fuck-college-i-need-sleep
  - Short Post/Pic - Comment Contain Pic
  https://devrant.com/rants/1758683/look-whos-inside
  - Short Post/Pic
  https://devrant.com/rants/1780720/rant
  - Short Post - Short Comment
  https://devrant.com/rants/1780962/atvirtualizationpeasants-atsysadmins-xenserver-or-proxmox-or-other-solutions-and
  - Short Post/Gif - Long Comment:
  https://devrant.com/rants/1667409/after-a-long-time-for-making-a-boiler-plate-now-im-ready-to-implement-game-logic

**Steps to reproduce:**
  1. Open one of the link above which contain the bug
  2. Resize the browser to a certain size (mine is below)
  3. Try to scroll from top to the very bottom both manually using click the scrollbar and scroll and use the mouse scroll / gesture scroll.

**Platform:** ...
  Firefox Quantum 62.0 on Ubuntu 18.04.1 64bit

**Additional Platform Info:**
  Browser Size 929x1763.6 (half of the screen, snapped)
  on monitor 1920x1080p

**Comment by Varbin** [comment] 2018-09-23 19:09
Can confirm except for "Short Post/Pic - Long Comment -- Bug only appear at the bottom".

Platform: Ubuntu 18.04 with FF 62, browser resolution of 958x921

**Comment by kaitoyonde** [comment] 2018-09-23 22:16
@Varbin does it appear if you scroll using mouse scroll / gesture scroll or manual scroll (click the scrollbar) ?

edited the issue in step to reproduce no 3

**Comment by xlf1024** [comment] 2018-09-25 21:35
Looks like #478 (Includes possible fix)

<del>Also, behavior seems to depend on whether or not there would be scrolling space for the avatar next to the rant text in initial configuration.</del>

Widths appear to be those where a scaled avatar is shown.

@wowotek Both Mouse and Scrollbar for me.

**Comment by jonasgeiler** [comment] 2018-09-26 07:05
Possible duplicate of #478 (thanks @xlf1024).

Will try to reproduce and then decide whether it is an actual duplicate or not.

**Comment by jonasgeiler** [comment] 2018-10-18 08:38
That indeed is a duplicate of #478. This bug is so weird haha

**Closed as completed by jonasgeiler** 2018-10-18 08:38 UTC
Labels: bug, Web app, design
