### ISSUE TITLE
Replying to a comment, cancelling, and hitting reply again doesn’t reset the tags

### ISSUE THREAD

**Issue by mmdelez** [devRant/devRant#189] opened 2017-10-18 10:00 UTC
On iOS when you reply to a comment, then cancel, and then hit reply on the same comment the tags don’t reset so it keeps adding a tag each time you do it.

**Comment by DFoxinator** [comment] 2017-10-22 17:18
Thanks for the report. Closing as duplicate of https://github.com/devRant/devRant/issues/39

**Closed by DFoxinator** 2017-10-22 17:18 UTC
