### ISSUE TITLE
Duplicate mentions in replies

### ISSUE THREAD

**Issue by IwraStudios** [devRant/devRant#56] opened 2017-08-11 22:28 UTC
Duplicate mentions
bug report:

Mentions multiple times when replying exiting(back to rant) and replying again

Android 7.1.2

Reproducable:
1. Meh

Special Conditions:
1. Slow internet connection
2. Nothing else

**Comment by DFoxinator** [comment] 2017-08-12 03:14
Thanks for the report. Closing as duplicate of https://github.com/devRant/devRant/issues/39

**Closed by DFoxinator** 2017-08-12 03:14 UTC
