### ISSUE TITLE
User's mentions not updating

### ISSUE THREAD

**Issue by XiovV** [devRant/devRant#138] opened 2017-10-03 09:15 UTC
Let's say that someone has a username like @user1, when someone mentions them in a comment their username is highlighted and it's clickable. But if they change the username to let's say @user2 their mention will no longer stay highlighted or clickable.

**Comment by olegrumiancev** [comment] 2017-10-03 10:25
@XiovV please read through a list of open issues. This is a duplicate of #129

**Comment by DFoxinator** [comment] 2017-10-03 13:39
Closing as duplicates of https://github.com/devRant/devRant/issues/129

**Closed by DFoxinator** 2017-10-03 13:39 UTC
