### ISSUE TITLE
[webapp/feature-request] subscribe to rants and mute notifications

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#372] opened 2018-04-02 15:58 UTC
It would be nice to have the same options as on mobile in the webapp, to be able to subscribe to a users rants, mute notifications etc.

**Comment by DFoxinator** [comment] 2018-04-04 06:09
Good call - closing as duplicate of https://github.com/devRant/devRant/issues/352

**Closed by DFoxinator** 2018-04-04 06:09 UTC
