### ISSUE TITLE
Mardown support

### ISSUE THREAD

**Issue by theCalcaholic** [devRant/devRant#163] opened 2017-10-11 16:46 UTC
Markdown support would be an amazing improvement for devRant - especially proper code rendering.

Thanks for the great work!

PS: `sudo add-markdown-support`

**Comment by cozyplanes** [comment] 2017-10-11 23:44
Possible duplicate of #27
Please search first as duplicate issues will be closed immediately

**Comment by DFoxinator** [comment] 2017-10-11 23:52
Thanks for the suggestion! This feature suggestion is being tracked here: https://github.com/devRant/devRant/issues/27 (feel free to discuss!)

**Closed by DFoxinator** 2017-10-11 23:52 UTC

**Comment by theCalcaholic** [comment] 2017-10-12 05:43
Ah, thank you. A search for 'markdown' did not yield any result, so I wasn't aware there's is a ticket already.
