### ISSUE TITLE
GIF player not stable

### ISSUE THREAD

**Issue by PaddiM8** [devRant/devRant#128] opened 2017-10-01 09:24 UTC
Often when I play gifs, it either goes completely black, or i can only see the moving pixels. Everything that stays the same is black. This happens 75% of the time. I'm on Android

**Comment by coolq1000** [comment] 2017-10-03 02:02
I agree, happens to me too. Please fix! Is it something to do with GIF's being single images, or certain file formats?

**Comment by aayush26** [comment] 2017-10-05 02:27
A major issue I guess. I have to always download in order to see the gifs properly. Will be great if fixed before the quantity of gifs increases.

**Comment by PerhapsSomeone** [comment] 2017-10-08 21:28
Can confirm. Happens almost every time now.

**Comment by DFoxinator** [comment] 2017-10-08 21:44
I'm working on trying to fix this. Unfortunately, the SDK we use, Titanium, doesn't have build in gif support. Because of that, we have to use this module: https://github.com/m1ga/com.miga.gifview

As you can see, the module has pretty much been abandoned. The Titanium module is build with a native Android module, this one: https://github.com/felipecsl/GifImageView

I'm guessing the issue is within the GifImageView module that's bundled with the Titanium module (com.miga.gifview), so I'm probably going to have to try to update that myself if there's even a working update. I'm also going to try to look for a different module to use maybe.

If anyone has any ideas, please let me know. This is a tricky one.

**Comment by DFoxinator** [comment] 2017-10-08 22:25
It appears this Titanium module is well-supported and his gif support: https://github.com/AndreaVitale/av.imageview 

I'm going to try implementing.

Does anyone have a link to a rant that has a gif that causes the broken behavior to happen consistently?

**Comment by DFoxinator** [comment] 2017-10-09 05:34
This should now be fixed in version 1.9.7.0 that was just released!

Please let me know if you encounter the issue again and thanks for the feedback on it.

**Closed by DFoxinator** 2017-10-09 05:34 UTC
Labels: Android app, bug, Priority 2

**Comment by PaddiM8** [comment] 2017-10-09 16:55
Ah okay! I was gonna link my CSS animation rant as it happened there a lot.
I also noticed uploading GIFs from phone doesn't even work, not sure if
it's fixed yet though. I'll try and post an issue if it's still an issue
for me!

2017-10-09 7:34 GMT+02:00 David Fox <notifications@github.com>:

**Comment by aayush26** [comment] 2017-10-13 17:02
The GIF player is quite stable now. Haven't came across the glittering or black gif issue as mentioned by others above.
Though the loading time as increase significantly. 
I am not familiar with Titanium. But I will also look into available gif player libraries.
