### ISSUE TITLE
[Feature Request] Swipe down to dismiss pictures.

### ISSUE THREAD

**Issue by GMR516** [devRant/devRant#326] opened 2018-02-21 08:15 UTC
Apollo app for Reddit and others do this. If you’re viewing media and you swipe down, it should dismiss it.

**Comment by Skayo** [comment] 2018-02-21 08:17
Yeah I miss that too

**Comment by DFoxinator** [comment] 2018-03-11 19:12
Closing as duplicate of https://github.com/devRant/devRant/issues/55

**Closed by DFoxinator** 2018-03-11 19:12 UTC
Labels: feature, iOS app
