### ISSUE TITLE
Comments on a rant double upon spamming refresh button

### ISSUE THREAD

**Issue by HTahboub** [devRant/devRant#453] opened 2018-06-15 13:30 UTC
So apparently, when you spam the refresh button within the rant, sometimes the comments in the rant double. This is happening on an iPhone 7, iOS 11. 

Oh and don't ask me why I was spamming the refresh button :D

**Comment by Skayo** [comment] 2018-07-14 19:36
Possible duplicate of #258

**Closed** 2018-07-15 13:11 UTC
Labels: bug, duplicate
