### ISSUE TITLE
[Android] Can't consistently scroll back up to profile

### ISSUE THREAD

**Issue by JoshuaCCampbell** [devRant/devRant#316] opened 2018-02-03 18:03 UTC
# Description
When viewing the profile page and a user scrolls to view Rants, "++'s", Comments, or Views, scrolling back up to view the profile information sometimes doesn't work. It stops at the top "post" and will only sometimes scroll up if you drag from the "Rants, ++'s, ..." bar twice in a row.

# Reproduce
_Only tested on Android with Google Pixel XL. App version 1.12.0.0_

- Go to a profile
- Scroll through some rants so that the option bar for "Rants, ++'s, Comments, View" locks to the top
- Scroll back up to the top of the page and get stuck at the top post

# Afternote
I'm not sure if this is either a partly intended feature or a bug with the Android layout, but it takes away from the user experience. as you must scroll to the top to see overall points among other options.

**Comment by Skayo** [comment] 2018-02-03 19:20
Just click on "Profile" at the top.
I think this was already reported somewhere...

**Comment by JoshuaCCampbell** [comment] 2018-02-03 19:28
While that works, it's a bit unintuitive imo. If it was reported I'd be interested in seeing the results. Personally it's not something I'd be happy with but to each their own :)

**Comment by cozyplanes** [comment] 2018-02-05 04:17
It is a limitation of the Titanium ScrollView, and it has been discussed before

**Comment by DFoxinator** [comment] 2018-02-13 05:50
Thanks for the thorough report. This is a known issue and a limitation in the ScrollView/SDK we use. Closing as a duplicate of this issue which is the same thing: https://github.com/devRant/devRant/issues/202

**Closed by DFoxinator** 2018-02-13 05:50 UTC
