### ISSUE TITLE
Attaching picture from "Edit" comment doesn't work

### ISSUE THREAD

**Issue by aswinramakrish** [devRant/devRant#144] opened 2017-10-04 18:03 UTC
I tried attaching a picture when I was trying to edit a comment. The picture seemed to have attached on the client side / device. But it wasn't available once the comment was posted (Probably look for the file while updating comment?)

**Comment by Skayo** [comment] 2018-07-15 23:52
Duplicate of #108

**Closed by Skayo** 2018-07-15 23:52 UTC
Labels: API, Android app, Priority 2, bug, iOS app
