### ISSUE TITLE
Cannot able to attach Image/GIF in comments [WebApp]

### ISSUE THREAD

**Issue by khateeb321** [devRant/devRant#254] opened 2017-11-21 08:07 UTC

**Comment by cozyplanes** [comment] 2017-11-21 13:58
Webapp overhaul coming soon, and i remember there is a similar issue saying the same problem.

**Comment by Skayo** [comment] 2017-11-23 07:51
Possible duplicate of #11

**Comment by DFoxinator** [comment] 2017-12-09 06:22
Thanks for the report - closing as duplicate of https://github.com/devRant/devRant/issues/11 and will be covered in new website.

**Closed by DFoxinator** 2017-12-09 06:22 UTC
