### ISSUE TITLE
Image zoom is broken

### ISSUE THREAD

**Issue by 7twin** [devRant/devRant#290] opened 2017-12-30 18:00 UTC
As the title says, zooming into pictures is broken with the newest update:
- pinch to zoom is disabled completely
- doubletap zooming allows to zoom only into one point, after that navigating to any direction shows the animation as if the image ends there

Android 7.1.2

**Comment by retnikt** [comment] 2018-01-04 18:17
Cannot reproduce, android 6.0.1

**Comment by kaesaecracker** [comment] 2018-01-04 21:53
Can reproduce, Android 8

**Comment by paradonym** [comment] 2018-01-08 14:35
Can't reproduce, OnePlus 3T, Android 8

but double tap zooming opens the "save image" menu which should open on singletap+hold (okay, which is a part of doubletap zooming...)

**Comment by DFoxinator** [comment] 2018-01-18 05:38
This was fixed in a previous version, so closing. Thanks.

**Closed by DFoxinator** 2018-01-18 05:38 UTC
Labels: Android app, Priority 1, bug
