### ISSUE TITLE
quick tab-change results in black/grey page

### ISSUE THREAD

**Issue by norbye** [devRant/devRant#200] opened 2017-10-23 15:27 UTC
When I change tabs quickly on my phone the content view part turns greyish, fixable by changing to another tab. Seems to work the same way no matter which tabs I change from. Sufficient to change tabs twice to achieve the undesired behaviour.

Device info: Samsung Galaxy S5, Android 6.0.1
App info: devRant v1.9.8.0

Screenshot:
![2017-10-23 15 17 10](https://user-images.githubusercontent.com/13599770/31897637-47dae92c-b817-11e7-832d-4adfb620a6dd.png)

**Comment by DFoxinator** [comment] 2017-10-24 02:00
Thanks for the report - closing as duplicate of https://github.com/devRant/devRant/issues/7

**Closed by DFoxinator** 2017-10-24 02:00 UTC
