### ISSUE TITLE
[BUG] Avatar Undefined on Web Version

### ISSUE THREAD

**Issue by C0D4-101** [devRant/devRant#362] opened 2018-03-23 09:09 UTC
When a user does not have an avatar,
the web version shows the avatar as:  https://avatars.devrant.com/undefined

Occurances:
* Notifs side bar
* Notifs page

**Comment by xlf1024** [comment] 2018-03-23 13:14
duplicate of #336

**Comment by DFoxinator** [comment] 2018-04-04 05:43
Fixed, logged in original issue.

**Closed by DFoxinator** 2018-04-04 05:43 UTC
